In [1]:
import pandas as pd

In [2]:
esa = pd.read_csv(r"C:\Users\ASUS\Downloads\Ele_Store1.csv")

In [4]:
esa.head(2)

,OrderID,OrderDate,UnitCost,Price,OrderQty,CostofSales,Sales,Profit,Channel,PromotionName,ProductName,Manufacturer,ProductSubCategory,ProductCategory,Region,City,Country
0,7077,13-09-2017,76.094968,304.00,9,684.854710,2714.7200,2029.865290,Store,European Spring Promotion,Contoso SLR Camera M143 Grey,"Contoso, Ltd",Digital SLR Cameras,Cameras and camcorders,Europe,Moscow,Russia
1,117,14-09-2017,7.491753,12.99,4,29.967011,50.1414,20.174389,Store,European Spring Promotion,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",MP4&MP3,Audio,Europe,Moscow,Russia

1) Query the list of columns?

In [6]:
esa.columns.to_list()

['OrderID',
 'OrderDate',
 'UnitCost',
 'Price',
 'OrderQty',
 'CostofSales',
 'Sales',
 'Profit',
 'Channel',
 'PromotionName',
 'ProductName',
 'Manufacturer',
 'ProductSubCategory',
 'ProductCategory',
 'Region',
 'City',
 'Country']

2) Query the top 5 rows?

In [10]:
esa.head(5)

,OrderID,OrderDate,UnitCost,Price,OrderQty,CostofSales,Sales,Profit,Channel,PromotionName,ProductName,Manufacturer,ProductSubCategory,ProductCategory,Region,City,Country
0,7077,13-09-2017,76.094968,304.00,9,684.854710,2714.7200,2029.865290,Store,European Spring Promotion,Contoso SLR Camera M143 Grey,"Contoso, Ltd",Digital SLR Cameras,Cameras and camcorders,Europe,Moscow,Russia
1,117,14-09-2017,7.491753,12.99,4,29.967011,50.1414,20.174389,Store,European Spring Promotion,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",MP4&MP3,Audio,Europe,Moscow,Russia
2,7018,15-09-2017,10.122338,159.99,9,91.101039,1395.1128,1304.011761,Store,European Spring Promotion,Contoso DVD 9-Inch Player Portable M300 Silver,"Contoso, Ltd",Movie DVD,"Music, Movies and Audio Books",Europe,Moscow,Russia
3,140,16-09-2017,0.576153,25.69,18,10.370759,462.4200,452.049241,Store,North America Spring Promotion,NT Bluetooth Stereo Headphones E52 Pink,Northwind Traders,Bluetooth Headphones,Audio,North America,Bellevue,United States
4,491,17-09-2017,108.508777,304.00,9,976.578991,2614.4000,1637.821009,Online,Asian Spring Promotion,Contoso SLR Camera M143 Grey,"Contoso, Ltd",Digital SLR Cameras,Cameras and camcorders,Asia,Beijing,China

3) Query the bottom 5 rows?

In [11]:
esa.tail(5)

,OrderID,OrderDate,UnitCost,Price,OrderQty,CostofSales,Sales,Profit,Channel,PromotionName,ProductName,Manufacturer,ProductSubCategory,ProductCategory,Region,City,Country
14995,22348,03-10-2058,16.240455,25.0,12,194.885455,300.0,105.114545,Store,Asian Summer Promotion,Contoso USB Cable M250 Blue,"Contoso, Ltd",Cameras & Camcorders Accessories,Cameras and camcorders,Asia,Osaka,Japan
14996,22349,04-10-2058,55.387212,999.0,10,553.872121,9990.0,9436.127879,Reseller,No Discount,WWI Projector 720p DLP56 White,Wide World Importers,Projectors & Screens,Computers,Europe,Paris,France
14997,22350,05-10-2058,363.634986,588.0,13,4727.254816,7408.8,2681.545184,Store,North America Holiday Promotion,"A. Datum SLR Camera 35"" X358 Gold",A. Datum Corporation,Digital SLR Cameras,Cameras and camcorders,North America,Ithaca,United States
14998,22351,06-10-2058,113.237461,279.0,12,1358.849536,3348.0,1989.150464,Online,Asian Summer Promotion,Adventure Works LCD20W M240 Black,Adventure Works,Monitors,Computers,Asia,Beijing,China
14999,22352,07-10-2058,10.936943,15.9,20,218.738862,318.0,99.261138,Store,No Discount,Contoso USB Wave Multi-media Keyboard E280 Black,"Contoso, Ltd",Computers Accessories,Computers,North America,Spring,United States

4) How many total number of orders placed?

In [14]:
esa.OrderID.count()

np.int64(15000)

5) What are the unique channels present and how many are there?

In [27]:
print(esa['Channel'].unique())
print(esa.Channel.nunique())

['Store' 'Online' 'Reseller' 'Catalog']
4

6) How many cities are there?

In [31]:
esa.City.nunique()

263

7) Query the unique Countries and count of the countries?

In [35]:
print(esa.Country.unique())
print(esa.Country.nunique())

['Russia' 'United States' 'China' 'United Kingdom' 'Canada' 'Germany'
 'Turkmenistan' 'France' 'Australia' 'Iran' 'Thailand' 'Kyrgyzstan'
 'South Korea' 'Pakistan' 'India' 'Japan' 'Ireland' 'Singapore' 'Armenia'
 'Greece' 'Romania' 'Denmark' 'Italy' 'Malta' 'Portugal' 'Slovenia'
 'Syria' 'Switzerland' 'Taiwan' 'the Netherlands' 'Poland' 'Bhutan'
 'Spain' 'Sweden']
34

8) Query the unique Regions and count of the regions?

In [38]:
print(esa.Region.unique())
print(esa.Region.nunique())

['Europe' 'North America' 'Asia']
3

9) Query the total cities count by Country and order it from highest count to lowest
count?

In [44]:
esa.groupby('Country')['City'].nunique().sort_values(ascending = False)

Country
United States      177
United Kingdom      15
Germany             10
France               7
Canada               6
Japan                6
Italy                5
China                5
India                3
Russia               3
South Korea          2
Australia            2
Armenia              1
Iran                 1
Greece               1
Denmark              1
Ireland              1
Bhutan               1
Poland               1
Pakistan             1
Malta                1
Kyrgyzstan           1
Singapore            1
Slovenia             1
Romania              1
Portugal             1
Sweden               1
Spain                1
Switzerland          1
Syria                1
Thailand             1
Taiwan               1
Turkmenistan         1
the Netherlands      1
Name: City, dtype: int64

10) How many products are there? Display count of products

In [48]:
print("Products:", esa.ProductName.unique())
print("Product Count:", esa.ProductName.nunique())

Products: ['Contoso SLR Camera M143 Grey' 'Contoso 512MB MP3 Player E51 Blue'
 'Contoso DVD 9-Inch Player Portable M300 Silver' ...
 'Contoso Rechargeable Battery Pack E310 Black'
 'Contoso 4-Line Corded Cordless Telephone M203 Grey'
 'Contoso 16GB Mp5 Player M1600 Red']
Product Count: 1638

11) Query the total sales and total profit?

In [54]:
print(esa.Sales.sum().round())
print(esa.Profit.sum().round())

55391760.0
31587437.0

12) Query the total sales by region and country?

In [60]:
esa.groupby(['Country','Region'])['Sales'].sum().reset_index().sort_values('Sales', ascending = False)

            Country         Region         Sales
32    United States  North America  3.163524e+07
4             China           Asia  7.557974e+06
7           Germany         Europe  4.314956e+06
6            France         Europe  2.628401e+06
31   United Kingdom         Europe  1.324267e+06
3            Canada  North America  1.148316e+06
13            Japan           Asia  9.583344e+05
1         Australia           Asia  6.326425e+05
9             India           Asia  5.984046e+05
20           Russia         Europe  4.342403e+05
30     Turkmenistan           Asia  4.123702e+05
10             Iran           Asia  3.679533e+05
27            Syria           Asia  3.296714e+05
12            Italy         Europe  3.168811e+05
16         Pakistan           Asia  2.965706e+05
29         Thailand           Asia  2.582489e+05
23      South Korea           Asia  2.506013e+05
28           Taiwan           Asia  1.890095e+05
0           Armenia           Asia  1.729347e+05
2            Bhutan           Asia  1.612916e+05
24            Spain         Europe  1.434332e+05
14       Kyrgyzstan           Asia  1.271148e+05
18         Portugal         Europe  1.263816e+05
15            Malta         Europe  1.122952e+05
33  the Netherlands         Europe  1.077465e+05
19          Romania         Europe  1.022789e+05
26      Switzerland         Europe  9.936224e+04
21        Singapore           Asia  9.922349e+04
11          Ireland         Europe  9.212368e+04
17           Poland         Europe  8.782953e+04
22         Slovenia         Europe  7.988141e+04
5           Denmark         Europe  7.914523e+04
25           Sweden         Europe  7.810665e+04
8            Greece         Europe  6.852796e+04

13) Query the total order qty by promotion name?

In [64]:
esa.groupby('PromotionName').OrderQty.sum()

PromotionName
Asian Holiday Promotion                   17004
Asian Spring Promotion                    10980
Asian Summer Promotion                     9768
European Back-to-Scholl Promotion          7363
European Holiday Promotion                12328
European Spring Promotion                 13205
No Discount                               80062
North America Back-to-School Promotion    39393
North America Holiday Promotion           30392
North America Spring Promotion            30631
Name: OrderQty, dtype: int64

14) Query the top 7 countries with sales from highest to lowest order?

In [76]:
esa.groupby('Country')['Sales'].sum().sort_values(ascending = False).head(7)

Country
United States     3.163524e+07
China             7.557974e+06
Germany           4.314956e+06
France            2.628401e+06
United Kingdom    1.324267e+06
Canada            1.148316e+06
Japan             9.583344e+05
Name: Sales, dtype: float64

15) How much the total sales happened in Asia region?

In [81]:
esa[esa['Region']=='Asia']['Sales'].sum().round()

np.float64(12412345.0)

16) How much total sales happened in Asia region and India?

In [85]:
esa[esa["Region"].isin(['Asia','India'])]['Sales'].sum()

np.float64(12412345.056499999)

17) How much profit got in Europe region and Denmark country?

In [89]:
esa[(esa['Region']=='Europe')&(esa['Country']=='Denmark')]['Profit'].sum()

np.float64(45194.06532283)

In [88]:
esa.query('Region=="Europe" and Country =="Denmark"')['Profit'].sum()

np.float64(45194.06532283)

18) Query the total order qty by Manufacturer and Product Name?

In [92]:
esa.groupby(['Manufacturer','ProductName']).OrderID.sum()

Manufacturer          ProductName
A. Datum Corporation  A. Datum Advanced Digital Camera M300 Azure                       83926
                      A. Datum Advanced Digital Camera M300 Black                       83967
                      A. Datum Advanced Digital Camera M300 Green                       90898
                      A. Datum Advanced Digital Camera M300 Grey                       122308
                      A. Datum Advanced Digital Camera M300 Orange                      74407
                                                                                        ...
Wide World Importers  WWI Wireless Transmitter and Bluetooth Headphones X250 Black      50294
                      WWI Wireless Transmitter and Bluetooth Headphones X250 Blue       70794
                      WWI Wireless Transmitter and Bluetooth Headphones X250 Red        44152
                      WWI Wireless Transmitter and Bluetooth Headphones X250 Silver     53445
                      WWI Wireless Transmitter and Bluetooth Headphones X250 White      44630
Name: OrderID, Length: 1638, dtype: int64

19) Query the top 7 products with orderqty and sales and show it descending order based on total orderqty?

In [96]:
esa.groupby('ProductName')[['OrderQty','Sales']].sum().sort_values(by = 'OrderQty', ascending = False).head(7)

                                                    OrderQty       Sales
ProductName
Contoso In-Line Coupler E180 Silver                     6780  22696.2500
Headphone Adapter for Contoso Phone E130 Silver         4680  46730.9223
Contoso Rubberized Snap-On Cover Hard Case Cell...      4580  21700.9050
Contoso In-Line Coupler E180 White                      4060  13588.4375
Contoso Rubberized Skin BlackBerry E100 Silver          3560  53319.8797
Cigarette Lighter Adapter for Contoso Phones E1...      3520  87912.3210
Contoso Rubberized Snap-On Cover Hard Case Cell...      3280  15534.4020

20) Query the total order quantity greater than 10000 by city?

In [98]:
esa.groupby('City')['OrderQty'].sum().reset_index().query('OrderQty>10000').sort_values(by ='OrderQty',ascending = False)

              City  OrderQty
25         Beijing     30547
170  North Harford     24806
30        Bethesda     20498
27          Berlin     13841
210        Seattle     12174

In [100]:
esa.groupby('City').OrderQty.sum().loc[lambda x:x > 10000].sort_values(ascending = False)

City
Beijing          30547
North Harford    24806
Bethesda         20498
Berlin           13841
Seattle          12174
Name: OrderQty, dtype: int64

21) Query the total sales less than 1000 by product, display it in ascending order?

In [102]:
esa.groupby('ProductName').Sales.sum().reset_index().query('Sales<10000').sort_values(by = 'Sales',ascending = True)

                                            ProductName      Sales
1353                        SV USB Data Cable E600 Grey    45.6950
1358               SV USB Sync Charge Cable E700 Silver    64.0780
1354                        SV USB Data Cable E600 Pink   100.4340
1352                       SV USB Data Cable E600 Black   124.2600
1357                 SV USB Sync Charge Cable E700 Blue   142.6830
...                                                 ...        ...
1147  Proseware Photo Smart All-in-One Printer M380 ...  9856.3500
312    Contoso 8GB Super-Slim MP3/Video Player M800 Red  9955.9725
1474  The Phone Company Touch Screen Phone 1600 TFT-...  9971.6500
220                   Adventure Works LCD20W M240 White  9974.2500
163             Adventure Works 32" LCD HDTV M130 White  9999.8000

[579 rows x 2 columns]

In [104]:
esa.groupby('ProductName').Sales.sum().loc[lambda x:x <10000].sort_values(ascending = True)

ProductName
SV USB Data Cable E600 Grey                                       45.6950
SV USB Sync Charge Cable E700 Silver                              64.0780
SV USB Data Cable E600 Pink                                      100.4340
SV USB Data Cable E600 Black                                     124.2600
SV USB Sync Charge Cable E700 Blue                               142.6830
                                                                  ...
Proseware Photo Smart All-in-One Printer M380 White             9856.3500
Contoso 8GB Super-Slim MP3/Video Player M800 Red                9955.9725
The Phone Company Touch Screen Phone 1600 TFT-2.2" L200 Gold    9971.6500
Adventure Works LCD20W M240 White                               9974.2500
Adventure Works 32" LCD HDTV M130 White                         9999.8000
Name: Sales, Length: 579, dtype: float64

22) Query the total profit greater than 200000 by product, display it in descending order?

In [105]:
esa.groupby('ProductName')['Profit'].sum().loc[lambda x:x > 200000].sort_values(ascending = False)

ProductName
Contoso Projector 1080p X980 White        320513.293550
Proseware Projector 1080p LCD86 White     315379.915450
Contoso Projector 1080p X980 Black        252654.597032
Proseware Projector 1080p LCD86 Black     232556.514538
Proseware Projector 1080p DLP86 Silver    228823.614999
Proseware Projector 1080p DLP86 Black     208705.101207
Name: Profit, dtype: float64

23) How much total sales happened in China and Beijing?

In [122]:
esa[esa['Country'].isin(['China','Russia'])]['Sales'].sum()

np.float64(7992214.054899999)

24) How much total sales happened in Asian Holiday Promotion?

In [126]:
esa[esa['PromotionName']=='Asian Holiday Promotion']['Sales'].sum()

np.float64(3615193.9905000003)

25) How much total profit value by Contoso, Ltd Manufacturer?

In [132]:
esa.query('Manufacturer=="Contoso, Ltd"')['Profit'].sum()

np.float64(5670159.660158278)

26) Query the total sales and total order qty by product category and order it by
Orderqty from highest to lowest?

In [133]:
esa.groupby('ProductCategory')[['Sales','OrderQty']].sum().sort_values(by = 'OrderQty',ascending = False)

                                      Sales  OrderQty
ProductCategory
Cell phones                    5.841156e+06     96074
Computers                      2.130697e+07     69425
Cameras and camcorders         1.704893e+07     43893
TV and Video                   9.107839e+06     22714
Music, Movies and Audio Books  1.057480e+06      9953
Audio                          1.029381e+06      9067

27) Query the total sales value in between 1057 and 26700 by Region?

In [144]:
esa.groupby('Region')['Sales'].sum().reset_index().query('1057<=Sales>=26700')

          Region         Sales
0           Asia  1.241235e+07
1         Europe  1.019586e+07
2  North America  3.278356e+07

28) How many orders placed in Pittsfield city?

In [152]:
esa[esa['City']=='Pittsfield']['OrderQty'].sum()

np.int64(349)

29) Query the total sales and total profit by region, country and city?

In [155]:
esa.groupby(['Region','Country','City'])[['Sales','Profit']].sum().reset_index()

            Region        Country         City         Sales        Profit
0             Asia        Armenia      Yerevan  1.729347e+05  1.119702e+05
1             Asia      Australia     Canberra  2.112396e+05  9.384047e+04
2             Asia      Australia       Sydney  4.214029e+05  2.503940e+05
3             Asia         Bhutan      Thimphu  1.612916e+05  8.817516e+04
4             Asia          China      Beijing  6.596953e+06  3.810007e+06
..             ...            ...          ...           ...           ...
258  North America  United States     Waukesha  1.953965e+05  9.556164e+04
259  North America  United States  Wheat Ridge  1.295698e+05  5.794578e+04
260  North America  United States   Winchester  9.426428e+04  5.261520e+04
261  North America  United States    Worcester  1.839504e+05  1.087016e+05
262  North America  United States       Yakima  1.008435e+05  7.079848e+04

[263 rows x 5 columns]

30) Query the total unit cost and total price by productcategory, productsubcategory
and Manufacturer?

In [160]:
esa.groupby(['ProductCategory','ProductSubCategory','Manufacturer'])[['UnitCost','Price']].agg('sum').reset_index()

,ProductCategory,ProductSubCategory,Manufacturer,UnitCost,Price
0,Audio,Bluetooth Headphones,Northwind Traders,4694.140924,10698.36
1,Audio,Bluetooth Headphones,Wide World Importers,5348.553816,12740.88
2,Audio,MP4&MP3,"Contoso, Ltd",15180.676953,37464.56
3,Audio,Recording Pen,Wide World Importers,10165.599158,22585.30
4,Cameras and camcorders,Camcorders,"Fabrikam, Inc.",286756.395516,705377.00
5,Cameras and camcorders,Cameras & Camcorders Accessories,"Contoso, Ltd",12221.056068,26301.12
6,Cameras and camcorders,Digital Cameras,A. Datum Corporation,88363.414849,210914.00
7,Cameras and camcorders,Digital SLR Cameras,A. Datum Corporation,55606.839775,148662.00
8,Cameras and camcorders,Digital SLR Cameras,"Contoso, Ltd",61069.829295,155672.00
9,Cameras and camcorders,Digital SLR Cameras,"Fabrikam, Inc.",64966.210095,174022.20
10,Cell phones,Cell phones Accessories,"Contoso, Ltd",1526.510851,3530.08
11,Cell phones,Home & Office Phones,"Contoso, Ltd",12044.658547,27389.09
12,Cell phones,Smart phones & PDAs,The Phone Company,103969.796452,239147.00
13,Cell phones,Touch Screen Phones,"Contoso, Ltd",12851.720868,27104.00
14,Cell phones,Touch Screen Phones,The Phone Company,55433.985480,130579.00
15,Computers,Computers Accessories,"Contoso, Ltd",16153.021031,35657.80
16,Computers,Computers Accessories,Southridge Video,12789.845684,24305.89
17,Computers,Desktops,Adventure Works,43576.939570,89568.35
18,Computers,Desktops,Wide World Importers,31821.889351,64659.00
19,Computers,Laptops,Adventure Works,93609.664408,224875.55
20,Computers,Laptops,"Fabrikam, Inc.",52102.113425,127405.35
21,Computers,Laptops,"Proseware, Inc.",26831.171937,59963.95
22,Computers,Laptops,Wide World Importers,45528.259167,119908.70
23,Computers,Monitors,Adventure Works,23132.559566,54600.00
24,Computers,Monitors,"Proseware, Inc.",17530.704507,42299.00
25,Computers,Monitors,Wide World Importers,22386.928271,58944.00
26,Computers,"Printers, Scanners & Fax","Proseware, Inc.",65123.253204,155502.00
27,Computers,Projectors & Screens,"Contoso, Ltd",78241.936027,198399.00
28,Computers,Projectors & Screens,"Proseware, Inc.",99812.740227,259541.00
29,Computers,Projectors & Screens,Wide World Importers,62842.407007,146677.00
30,"Music, Movies and Audio Books",Movie DVD,"Contoso, Ltd",16690.866047,44897.45
31,"Music, Movies and Audio Books",Movie DVD,Southridge Video,17559.035965,42566.69
32,TV and Video,Car Video,Southridge Video,84685.148227,179049.00
33,TV and Video,Home Theater System,"Contoso, Ltd",97944.784475,205953.00
34,TV and Video,Home Theater System,"Litware, Inc.",87195.387626,187306.80
35,TV and Video,Televisions,Adventure Works,71821.432011,174949.73
36,TV and Video,VCD & DVD,Southridge Video,8797.508772,18504.60