In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv(r'C:\Users\ASUS\Downloads\TATA_TB1.csv',  encoding='latin1')

In [3]:
df2 = pd.read_csv(r"C:\Users\ASUS\Downloads\TATA_TB2.csv")

1) Write a query to calculate the total records in two tables?

In [4]:
total_records = df1.shape[0]+df2.shape[0] #or len(df1)+len(df2)
print(total_records)

12164

2) Write a query to calculate the total unique count of customers?

In [5]:
df1.CustomerName.nunique()

792

3) Write a query to fetch the oldest order date and latest order date?

In [6]:
print("Latest Order Date:", df1['OrderDate'].max())
print("Oldest Order Date:", df1['OrderDate'].min())

Latest Order Date: 2014-12-31
Oldest Order Date: 2011-01-01

4) Write query to get unique years?

In [7]:
df1['OrderDate'] =pd.to_datetime(df1['OrderDate'])
df1['OrderDate'].dt.year.nunique()

4

5) Write a query to get the no. of regions and display the region names?

In [8]:
print("Region Names:", df1.Region.unique())
print("Total Regions:", df1.Region.nunique())

Region Names: ['North' 'Central' 'South']
Total Regions: 3

6) Write a query to get the no. of countries and display the country names?

In [9]:
print("Country Names:", df1.Country.unique())
print("Total Countries:", df1.Country.nunique())

Country Names: ['Sweden' 'United Kingdom' 'France' 'Italy' 'Austria' 'Spain' 'Germany'
 'Netherlands' 'Denmark' 'Belgium' 'Norway' 'Portugal' 'Switzerland'
 'Ireland' 'Finland']
Total Countries: 15

7) Write a query to get the no. of states and display the state names?

In [10]:
print("State Names:", df1.State.unique())
print("Total States:", df1.State.nunique())

State Names: ['Stockholm' 'England' 'Auvergne-Rhône-Alpes' "Provence-Alpes-Côte d'Azur"
 'Languedoc-Roussillon-Midi-Pyrénées' 'Liguria' 'Vienna' 'Murcia'
 'Lower Saxony' 'South Holland' 'Västra Götaland' 'Hovedstaden'
 'Valenciana' 'South Denmark' 'Lombardy' 'Sicily' 'Ile-de-France'
 'North Rhine-Westphalia' 'Flemish Brabant' 'Tuscany' 'Emilia-Romagna'
 'Madrid' 'Oslo' 'Lisboa' 'Saxony' 'Andalusía' 'Catalonia'
 'Alsace-Champagne-Ardenne-Lorraine' 'Bavaria' 'Uppsala'
 'Nord-Pas-de-Calais-Picardie' 'Hesse' 'Overijssel' 'Basel-Stadt'
 'Bourgogne-Franche-Comté' 'Zürich' 'Dublin' 'Lazio' 'Namur'
 'North Holland' 'Berlin' 'Baden-Württemberg'
 'Aquitaine-Limousin-Poitou-Charentes' 'Uusimaa' 'Apulia' 'Saxony-Anhalt'
 'Rogaland' 'Sardinia' 'Drenthe' 'Mecklenburg-Vorpommern' 'North Brabant'
 'Umbria' 'Geneva' 'Veneto' 'Normandy' 'Scotland' 'Coimbra'
 'Castile and León' 'Gelderland' 'Hamburg' 'Brandenburg'
 'Pays de la Loire' 'Antwerp' 'Bremen' 'Thuringia' 'Porto' 'Utrecht'
 'Castile-La Mancha' 'Brittany' 'Campania' 'Cork' 'Groningen'
 'East Flanders' 'Ceuta' 'Halland' 'Navarra' 'Rhineland-Palatinate'
 'Limburg' 'Upper Austria' 'Schleswig-Holstein' 'Tyrol' 'Corsica'
 'Trentino-Alto Adige' 'Vaud' 'Piedmont' 'Calabria' 'Galicia' 'Buskerud'
 'Centre-Val de Loire' 'Styria' 'Abruzzi' 'Basque Country' 'Cantabria'
 'Asturias' 'Finland Proper' 'Central Jutland' 'Wales' 'Kymenlaakso'
 'Friesland' 'Braga' 'Aveiro' 'Marche' 'Saarland' 'Skåne'
 'Friuli-Venezia Giulia' 'Balearic Islands' 'Extremadura' 'Basilicata'
 'Hedmark' 'Hainaut' 'Melilla' 'Salzburg' 'Carinthia' 'Zeeland'
 'Hordaland' 'Lucerne' 'Liège' 'West Flanders' 'Bern' 'Brussels'
 'Södermanland' 'Zealand' 'Galway' 'Värmland' 'Vest-Agder' 'St. Gallen'
 'Setúbal']
Total States: 127

8) Write a query to get the no. of cities and display the city names?

In [11]:
print("City Names:", df1['City'].unique())
print("Total Cities:", df1['City'].nunique())

City Names: ['Stockholm' 'Southport' 'Valence' 'Birmingham' 'Echirolles'
 'La Seyne-sur-Mer' 'Toulouse' 'Genoa' 'Vienna' 'Murcia' 'Woking' 'Lohne'
 'Leicester' 'Sheffield' 'Dordrecht' 'Gothenburg' 'Langen' 'Copenhagen'
 'Gandia' 'Esbjerg' 'Sesto San Giovanni' 'Trapani' 'Villiers-sur-Marne'
 'Bielefeld' 'Leuven' 'Prato' 'Gela' 'Bologna' 'Menden' 'Maisons-Alfort'
 'Madrid' 'Oslo' 'Lisbon' 'Draguignan' 'Halle' 'Parma' 'Dresden' 'Seville'
 'Torrevieja' 'Barcelona' 'London' 'Reims' 'Rosenheim' 'Uppsala' 'Nice'
 'Boulogne-sur-Mer' 'La Crau' 'Siena' 'Frankfurt' 'Almelo' 'Basel'
 'Coslada' 'Marseille' 'Hanover' 'Elda' 'Hardenberg' 'Muret' 'Beaune'
 'Paris' 'Castrop-Rauxel' 'Milan' 'Zurich' 'Grosseto' 'Dublin' 'Rome'
 'Namur' 'Zaanstad' 'Bochum' 'Colmar' 'Farnborough' 'Berlin' 'Rimini'
 'Baden-Baden' 'Pforzheim' 'Coventry' 'Pessac' 'Helsinki' 'Bonn' 'Leipzig'
 'Tourcoing' 'Bari' 'Magdeburg' 'Noisy-le-Sec' 'Stavanger' 'Cagliari'
 'Marsala' 'Emmen' 'Augsburg' 'Stralsund' 'Carcassonne' 'Munich' 'Wigan'
 'Helmond' 'Castres' 'Foligno' 'Hamm' 'Troisdorf' 'Geneva'
 'Newcastle upon Tyne' 'Treviso' 'Le Havre' 'Edinburgh' 'Saint-Priest'
 'Lattes' 'Le Blanc-Mesnil' 'Essen' 'Coimbra' 'Ponferrada' 'Nacka' 'Crewe'
 'Duisburg' 'Montigny-le-Bretonneux' 'Apeldoorn' 'Brindisi' 'Hamburg'
 'Fontainebleau' 'Riom' 'Limoges' 'Potsdam' 'Lowestoft' 'Elx' 'Sannois'
 'Rotterdam' 'Halifax' 'Rubí' 'Le Petit-Quevilly' 'Nijmegen' 'Chaumont'
 'Vernon' 'Cholet' 'Cesena' 'Nogent-sur-Oise' 'Antwerp' 'Pontoise'
 'Krefeld' 'Bremen' 'Moers' 'Ulm' 'Erfurt' 'Watford' 'Alcobendas'
 'Amsterdam' 'Porto' 'Champigny-sur-Marne' 'Dudley' 'Utrecht' 'Bordeaux'
 'Messina' 'Vincennes' 'Neuilly-sur-Marne' 'Argenteuil'
 "Quartu Sant'Elena" 'Toledo' 'Rennes' 'Breda' 'Naples' 'Lisieux'
 'Portsmouth' 'Pulheim' 'Luton' 'Talence' 'Deuil-la-Barre' 'Lyon' 'Cork'
 'Warrington' 'Groningen' 'Strasbourg' 'Oyonnax' 'Cologne' 'Colchester'
 'Drancy' 'Mannheim' 'Evreux' 'Norwich' 'Southend-on-Sea' 'Palermo'
 'Worcester' 'Ghent' 'Chatham' 'Ceuta' 'Remscheid' 'Hautmont' 'Lille'
 'Aprilia' 'Thonon-les-Bains' 'Vitry-sur-Seine' 'Venice' 'Bamberg'
 'Bolton' 'Halmstad' 'Odense' 'Wallasey' 'Lormont' 'Wolverhampton'
 'Valladolid' 'Pamplona' 'Mansfield' 'Perpignan' 'Weston-super-Mare'
 'Hagen' 'Minden' 'Ludwigshafen am Rhein' 'Zwolle' 'Roermond' 'Freiburg'
 'Roanne' 'Las Rozas de Madrid' 'Mont-de-Marsan' 'Gallarate' 'Wiesbaden'
 'Saint-Laurent-du-Var' 'Glasgow' 'Torremolinos' 'Anglet' 'Bressuire'
 'Gronau' 'Rochdale' 'Villingen-Schwenningen' 'Les Lilas' 'Linz'
 'Langenhagen' 'Cottbus' 'Bideford' 'Landerneau' 'Derby' 'Vantaa'
 'Aylesbury' 'Hastings' 'Vila Nova de Gaia' 'Stuttgart' 'Reus' 'Cerignola'
 'La Madeleine' 'The Hague' 'Rostock' 'Leverkusen' 'Cestas' 'Huddersfield'
 'Passau' 'Biarritz' 'Aix-en-Provence' 'Ashford' 'Kiel' 'Innsbruck'
 'Belfort' 'Fontenay-aux-Roses' 'Courbevoie' 'Ajaccio' 'Harrow' 'Arnsberg'
 'Altamura' 'Vallauris' 'Valencia' 'Trento' 'Sunderland' 'Tarragona'
 'Como' 'Manchester' 'Schwerin' 'Harrogate' 'Sant Boi de Llobregat'
 'Arnhem' 'Cergy' 'Noisy-le-Grand' 'Lausanne' 'Bristol' 'Saint-Avold'
 'Montpellier' 'High Wycombe' 'Lucca' 'Turin' 'Menton' 'Crotone' 'Vertou'
 'Paisley' 'Vigo' 'Roubaix' 'Taverny' 'Chester' 'Vicenza' 'Wuppertal'
 'Herne' 'Drammen' 'Jena' 'Friedrichshafen' 'Wattrelos' 'Orsay' 'Dreux'
 "Reggio nell'Emilia" 'Salamanca' 'Oberhausen' 'Lugo' 'Neuilly-sur-Seine'
 'Offenbach' 'Alicante' 'Northampton' 'Darlington' 'Zwickau'
 'Aulnay-sous-Bois' 'Karlsruhe' 'Loughborough' 'Gera' 'Vignola' 'Poissy'
 'Blackburn' 'Cumbernauld' 'Plymouth' 'Catania' 'Leeds' 'Bolzano'
 'La Baule-Escoublac' 'York' 'Molfetta' 'Verdun' 'Birkenhead' 'Beauvais'
 'Arras' 'Littlehampton' 'Saint-Malo' 'Dijon' 'Carrara' 'Graz' 'Quimper'
 'Gloucester' 'Massa' 'Dos Hermanas' 'Pescara' 'Novara' 'Montreuil'
 'Stockton-on-Tees' 'Recklinghausen' 'Waterlooville' 'Frontignan' 'Trier'
 'Heilbronn' 'Aachen' 'Bilbao' 'Saint-Ouen' 'Alfortville' 'Preston'
 'Ferrara' 'Clermont-Ferrand' 'Digne-les-Bains' 'Pozzuoli' 'Slough'
 'Norderstedt' 'Nuremberg' 'Ipswich' 'Allauch' 'Cinisello Balsamo'
 'Hildesheim' 'Laval' 'Ercolano' 'Longjumeau' 'Herten' 'Stockport'
 'Girona' 'Santander' 'Mougins' 'Rovigo' 'Vannes' 'Antibes' 'Hattingen'
 'Guildford' 'Fuengirola' 'Florence' 'Velbert' 'Grigny' 'Haarlem' 'Mijas'
 'Hove' 'Genk' 'Villeurbanne' 'Siegen' 'Grenoble' 'Cartagena' 'Greifswald'
 'Firminy' 'Foggia' 'Vittoria' 'Nottingham' 'Lunel' 'Peterborough'
 'Ravenna' 'Cannes' 'Amadora' 'Oviedo' 'La Rochelle' 'Rosny-sous-Bois'
 'Marly-le-Roi' 'Turku' 'Walsall' 'Herford' 'Nantes' 'Oullins' 'Valdemoro'
 'Bayonne' 'Manresa' 'Dortmund' 'Bry-sur-Marne' 'Molina de Segura'
 'Regensburg' 'Zamora' 'Blackpool' 'Villeparisis' 'Verona' 'Darmstadt'
 'Plaisance-du-Touch' 'Cheltenham' 'Givors' 'Tamworth' 'Rouen' 'Marbella'
 'Kassel' 'Enschede' 'Neubrandenburg' 'Haninge' 'Carlisle' 'Laon'
 'Iserlohn' 'Assen' 'East Kilbride' 'Runcorn' 'Gosport' 'Rillieux-la-Pape'
 'Montrouge' 'Corbeil-Essonnes' 'Fiumicino' 'Agen' 'Aschaffenburg'
 'Sandnes' 'Mulhouse' 'Hinckley' 'Randers' 'Perugia' 'Sassari' 'Cambridge'
 'Busto Arsizio' 'Chartres' 'Puertollano' 'Vanves' 'Dundee' 'Odivelas'
 'Nanterre' 'Kingswood' 'Orihuela' 'Meyzieu' 'Wolfsburg' 'Barry' 'Viersen'
 'Tarbes' 'Weimar' 'Outreau' 'Eindhoven' 'Dorsten' 'Gateshead' 'Tilburg'
 'Aberdeen' 'Malakoff' 'Espoo' 'Conflans-Sainte-Honorine' 'Bradford'
 'Euskirchen' 'Poole' 'Cardiff' 'Benidorm' 'Hasselt' 'Mauguio' 'Rotherham'
 'West Bromwich' 'Annecy' 'Montesson' 'Erftstadt' 'Marano di Napoli'
 'Saint-Michel-sur-Orge' 'Oxford' 'Frederiksberg' 'Dormagen' 'Parla'
 'Capelle aan den IJssel' 'Lons-le-Saunier' 'Schiedam' 'Kotka'
 'Leeuwarden' 'Chelles' 'Chemnitz' 'Winterthur' 'Huddinge' 'Guimarães'
 'Tremblay-en-France' 'La Teste-de-Buch' 'Velletri' 'Cremona' 'Rugby'
 'Narbonne' 'Tours' 'Villemomble' 'Irun' 'Burgos' 'Harlow' 'Fareham'
 'Cercola' 'Mantes-la-Jolie' 'Soissons' 'Barletta' 'San Fernando' 'Imola'
 'Avignon' 'Brest' 'Angers' 'Clamart' 'Oldenburg' 'Nancy' 'Palaiseau'
 'Heidelberg' 'Guyancourt' 'Widnes' 'Bonneuil-sur-Marne'
 'Mont-Saint-Aignan' 'Marl' 'Feira' 'Munster' 'San Sebastian' 'Massy'
 'Brandenburg' 'Lens' 'Le Bouscat' 'Aubervilliers' 'El Escorial'
 'Jerez de la Frontera' 'Alphen aan den Rijn' 'Villefontaine' 'Bottrop'
 'Boulogne-Billancourt' 'Pesaro' 'Taunton' 'Villiers-le-Bel' 'Ennigerloh'
 'Granada' 'Solna' 'Pomezia' 'Creil' 'Paderborn' 'Valenciennes' 'Tallaght'
 'Amersfoort' 'Marignane' 'Neunkirchen' 'Bourges' 'Savigny-le-Temple'
 'Abbeville' 'Sale' 'Eastbourne' 'Modena' 'Bad Waldsee' 'Gummersbach'
 'Vichy' 'Helsingborg' 'Pontivy' 'Bondy' 'Cuneo' 'Flers' 'Emden'
 'Colomiers' 'Annemasse' 'Granollers' 'Chesterfield' 'Lippstadt' 'Taranto'
 'Mâcon' 'Sorgues' 'Bedford' 'Domont' 'Millau' 'Brive-la-Gaillarde'
 'Douai' 'Lincoln' 'Zeist' 'Waiblingen' 'Kerpen' 'Lagny-sur-Marne' 'Getxo'
 'Gonesse' 'Bury' 'Livry-Gargan' 'Montargis' 'Tulle' 'Mitry-Mory'
 'Mechelen' 'Dewsbury' 'Capua' 'Le Plessis-Robinson' 'Meudon'
 'Basingstoke' 'Montecatini Terme' 'Huelva' 'Swindon' 'Bagneux'
 'Gillingham' 'Les Mureaux' 'Schiltigheim' 'Günzburg' 'Unna'
 'Coudekerque-Branche' 'Erlangen' 'Caen' 'Deventer' 'Saint-Nazaire'
 'Calais' 'Le Mans' 'Bayreuth' 'Evry' 'Swansea' 'Margate'
 'Faches-Thumesnil' 'Bergheim' 'Hamme' 'Worms' 'Pontault-Combault'
 'Eggenstein-Leopoldshafen' 'Grevenbroich' 'Trieste' 'Neuilly-Plaisance'
 'Sittard' 'Spijkenisse' 'Les Ulis' 'Palma de Mallorca' 'Chelmsford'
 'Ferndown' 'Saint-Cloud' 'Choisy-le-Roi' 'Agde' 'Saint-Louis'
 'Hazebrouck' 'Badajoz' 'Moncalieri' 'Amiens' 'Acireale' 'Hilversum'
 'Clichy' 'Albertville' 'Bourgoin-Jallieu' 'Potenza' 'Torre del Greco'
 'Oldham' 'Saint-Denis' 'Liverpool' 'Sabadell' 'Montmorency'
 'Stoke-on-Trent' 'Albacete' 'Auxerre' 'Talavera de la Reina' 'Bisceglie'
 'Northwich' 'Issy-les-Moulineaux' 'Bracknell' 'Vitoria' 'Istres'
 'El Ejido' 'Toulon' 'Latina' 'Antony' 'Rhondda' 'Hilden' 'Hamar'
 'Castelldefels' 'Sanary-sur-Mer' 'Worthing' 'Majadahonda' 'Cártama'
 'Arezzo' 'Fontaine' 'Getafe' 'Chilly-Mazarin' 'Basildon' 'Charleroi'
 'Pau' 'Melilla' 'Grasse' 'Maisons-Laffitte' 'Gap' 'Bergen op Zoom'
 'Puteaux' 'Hereford' 'Battipaglia' 'Clydach' 'Meaux' 'Oosterhout'
 'Salzburg' 'Palencia' 'Rochefort' 'Portici' 'Blanquefort'
 'Saint-Herblain' 'Lomme' 'Lorca' 'Bron' 'Bergamo' 'Villach' 'Cognac'
 'Haguenau' "Cournon-d'Auvergne" 'Solihull' 'El Prat de Llobregat'
 'Solingen' 'Maidenhead' 'Exeter' 'Fano' 'Auch' 'Terneuzen'
 'Saint-Chamond' 'Mainz' 'Veenendaal' 'Versailles' 'Six-Fours-les-Plages'
 'Castelnau-le-Lez' 'Ermont' 'Monza' 'Gradignan' 'Ingolstadt' 'Thionville'
 'Morley' 'Bergen' 'Tournefeuille' 'Athis-Mons' 'Cachan' 'Cagnes-sur-Mer'
 'Civitavecchia' 'Boscoreale' 'Brescia' 'Arles' 'Marina di Carrara'
 'Gennevilliers' 'Ancona' 'Cluses' 'Le Pontet' 'Lucerne' 'Offenburg'
 'Reading' 'Hartlepool' 'Barnsley' 'Forst' 'Bergisch Gladbach' 'Lund'
 'Faenza' 'Clichy-sous-Bois' 'Heerlen' 'Montauban' 'Carvin'
 'Villeneuve-Saint-Georges' 'Albi' 'Sevran' 'Saint-Dizier' 'Kettering'
 'Bournemouth' 'Trani' 'Sarreguemines' 'Tivoli' 'Letchworth' 'Klagenfurt'
 'Reutlingen' 'Pontevedra' 'Saumur' 'Poitiers' 'Neuwied' 'Fresnes'
 'Chioggia' 'Montbrison' 'Melun' 'Bourg-en-Bresse' 'Verviers' 'Velsen'
 'Forbach' 'Delmenhorst' 'Saint-Germain-en-Laye' 'Roosendaal' 'Metz'
 'Wetzlar' 'Roeselare' 'Miramas' 'Vlaardingen' 'Burnley' 'Nieuwegein'
 'Thiais' 'Santiago de Compostela' 'Sète' 'La Ciotat' 'Pistoia' 'Redditch'
 'Wetter (Ruhr)' 'Aalst' 'Argentan' 'Viroflay' 'Celle' 'Niort' 'Martigues'
 'Middlesbrough' 'Lanester' 'Berne' 'Teramo' 'Villeneuve-le-Roi'
 'Great Yarmouth' 'Legnano' 'Franconville' 'Roissy-en-Brie' 'Stains'
 'Ratingen' 'Bar-le-Duc' 'Annonay' 'Wakefield' 'Cuenca' 'Seraing' 'Acerra'
 'Barakaldo' 'Uithoorn' 'Maidstone' 'Halesowen' 'Les Pavillons-sous-Bois'
 'Delft' 'Caserta' 'Rueil-Malmaison' 'Gladbeck' 'Dartford' 'Benevento'
 'Carpi' 'Saint-Brieuc' 'Rambouillet' 'Koblenz' 'Berck'
 'Illkirch-Graffenstaden' 'Hengelo' 'Witten' 'Osny' 'Cambrai' 'Avellino'
 'Shrewsbury' 'Flensburg' 'Mons-en-Baroeul' 'Aalen' 'Fuenlabrada'
 'Stafford' 'Mouscron' 'Sucy-en-Brie' 'Moissy-Cramayel' 'Brussels'
 'Denain' 'Schiffweiler' 'Gelsenkirchen' 'Le Chesnay' 'Bognor Regis'
 'Cosenza' 'Vaulx-en-Velin' 'Pantin' 'Afragola' 'Kidderminster' 'Bath'
 'Les Herbiers' 'Sonneberg' 'Asti' 'Bastia' 'Falconara Marittima' 'Chieti'
 'Dinslaken' 'Wels' 'Annecy-le-Vieux' 'Eskilstuna' 'Kortrijk' 'Kalundborg'
 'Moulins' 'Oss' 'Varese' 'Dieppe' 'Saint-Gratien' 'Nuneaton' 'Alkmaar'
 'Wasquehal' 'Colombes' 'Galway' 'Dunstable' 'Vigneux-sur-Seine'
 'Badalona' 'Sarcelles' 'Capannori' 'Brighton' 'Guadalajara' 'Estepona'
 'Wilhelmshaven' 'Den Helder' 'Detmold' 'Bayeux' 'Pamiers' 'Kilwinning'
 'Fleury-les-Aubrais' 'Carquefou' 'Ludwigsburg' 'Casoria' 'Trappes'
 'Maastricht' 'Bagnolet' 'Limay' 'Agrigento' 'Libourne'
 'Saint-Pol-sur-Mer' 'Andria' 'Crawley' 'Pisa' 'Alessandria' 'Avion'
 'Levallois-Perret' 'Barneveld' 'Guidonia Montecelio' 'Lecce' 'Purmerend'
 'Anzio' 'Karlstad' 'Voiron' 'Ronchin' 'Ludwigsfelde' 'La Spezia'
 'San Severo' 'Gagny' 'Saint-Genis-Laval' 'Torcy' 'Villeneuve-sur-Lot'
 'Bruges' 'Treviglio' 'Sonderborg' 'Garbsen' 'Washington' 'Fulda'
 'Fontenay-sous-Bois' 'Upplands Väsby' 'Kristiansand' 'Pertuis'
 'Cormeilles-en-Parisis' 'St. Gallen' 'Doncaster'
 'Chiclana de la Frontera' 'Borken' "Villeneuve-d'Ascq" 'Langenfeld'
 'Mantes-la-Ville' 'Ragusa' 'Salon-de-Provence' 'Castellammare di Stabia'
 'Leiden' 'Ivry-sur-Seine' 'Friedberg' 'Plaisir' 'Briton Ferry'
 'Saint-Quentin' 'Senlis' 'Stourbridge' 'Hemel Hempstead'
 'Saint-Jean-de-la-Ruelle' 'Tournai' 'Sindelfingen' 'Ploemeur' 'Vitrolles'
 'Coulommiers' 'Piacenza' 'Epinal' 'Doetinchem' 'Villejuif' 'Willich'
 'Issoire' 'Louviers' 'Peer' 'Loures' 'South Shields' 'Sartrouville'
 'Carpentras' 'Concarneau' 'Torquay' 'Kaiserslautern' 'Savona' 'Gravesend'
 'Cuxhaven' 'Viterbo' 'Modica' 'Le Pré-Saint-Gervais' 'Braga'
 'Aix-les-Bains' 'Landskrona' 'Livingston' 'Montgeron' 'Halluin'
 'Manfredonia' 'Segovia' 'Pierrefitte-sur-Seine' 'Lorient' 'Le Cannet'
 'Venlo' 'Ponteareas' 'Vigevano' 'Arrentela' 'Clacton-on-Sea' 'Sagunto']
Total Cities: 999

9) Write a query to calculate the total count of products?

In [12]:
df2['ProductName'].nunique()

1810

10) Write a query to calculate total sales, total profit and total order quantity?

In [13]:
df2[['Sales','Profit','OrderQuantity']].sum()

Sales            2348482
Profit            283240
OrderQuantity      30354
dtype: int64

11) Write a query to calculate the total sales amount, total order quantity for each category. Display the category, total sales, and total order qty and order by total sales from highest to lowest?

In [14]:
df2.groupby('Category')[['Sales','OrderQuantity']].sum().sort_values(by = 'Sales', ascending = False)

                  Sales  OrderQuantity
Category
Technology       886015           5811
Office Supplies  823658          19902
Furniture        638809           4641

12) Write a query to calculate the total profit amount for each category. Display the
category, total profit, and total order qty and order by total profit from highest to lowest?

In [15]:
df2.groupby('Category')[['Profit','OrderQuantity']].sum().sort_values(by = 'Profit', ascending= False)

                 Profit  OrderQuantity
Category
Office Supplies  124952          19902
Technology       108554           5811
Furniture         49734           4641

13) Write a query to fetch the subcategories where total sales are greater than 100000?

In [16]:
df2.groupby('SubCategory')['Sales'].sum().reset_index().query('Sales>100000')

    SubCategory   Sales
0   Accessories  131309
1    Appliances  209900
2           Art  127184
4     Bookcases  294396
5        Chairs  186698
6       Copiers  290081
11     Machines  182066
13       Phones  282559
14      Storage  272489

14) Write a query to fetch the products where total profit is greater than 2500 and sort it
based on profit from highest to lowest??

In [17]:
df2.groupby('ProductName').Profit.sum().loc[lambda x:x>2500].sort_values(ascending = False)

ProductName
Nokia Smart Phone, Full Size               7583
Hoover Stove, Red                          6139
Hamilton Beach Stove, Silver               5778
SAFCO Executive Leather Armchair, Black    4324
Safco Classic Bookcase, Metal              4183
Cisco Smart Phone, with Caller ID          4055
Brother Fax Machine, Laser                 3918
Eldon Lockers, Industrial                  3611
Cisco Smart Phone, Cordless                3388
Hamilton Beach Stove, Red                  2738
Belkin Router, USB                         2677
Nokia Smart Phone, Cordless                2633
Cuisinart Refrigerator, Black              2627
Eldon File Cart, Single Width              2539
Name: Profit, dtype: int64

15) Write a query to get the total sales and total profit for Office Supplies category?

In [18]:
df2[df2['Category']=='Office Supplies'][['Profit','Sales']].sum()

Profit    124952
Sales     823658
dtype: int64

16) Write a query to get the total sales and total profit for Furniture category and Tables, Bookcases sub-categories ?

In [19]:
df2.query("Category == 'Furniture' and SubCategory in ['Tables', 'Bookcases']")[['Sales', 'Profit']].sum()

Sales     383874
Profit     22924
dtype: int64

17) Write a query to get the total sales and total profit for Technology category and the
Accessories, Copiers, Phones sub-categories ?

In [20]:
df2[(df2['Category']=='Technology')&(df2['SubCategory'].isin(['Accessories', 'Copiers', 'Phones']))][['Sales','Profit']].sum()

Sales     703949
Profit     97236
dtype: int64

18) Write a query to get total sales and total profit by Region, Segment and sort the sales from highest to lowest??

In [21]:
df_merged = df2.merge(df1, on ='OrderID')
df_merged.head(2)

,OrderID,ProductName,Discount,Sales,Profit,OrderQuantity,Category,SubCategory,OrderDate,CustomerName,City,Country,Region,Segment,ShipDate,ShipMode,State,lon,lat
0,BN-2011-7407039,"Enermax Note Cards, Premium",0.5,45,-26,3,Office Supplies,Paper,2011-01-01,Ruby Patel,Stockholm,Sweden,North,Home Office,2011-01-05,Economy Plus,Stockholm,18.068581,59.329324
1,AZ-2011-9050313,"Dania Corner Shelving, Traditional",0.0,854,290,7,Furniture,Bookcases,2011-01-03,Summer Hayward,Southport,United Kingdom,North,Consumer,2011-01-07,Economy,England,-3.010113,53.645708

In [22]:
df_merged.groupby(['Region','Segment'])[['Sales','Profit']].sum().sort_values(by = 'Sales',ascending = False)

                      Sales  Profit
Region  Segment
Central Consumer     701892   82146
        Corporate    396437   52115
North   Consumer     267955   35686
South   Consumer     266435   29615
Central Home Office  216924   23375
South   Corporate    177709   13647
North   Corporate    163991   26872
        Home Office   84033    8881
South   Home Office   73106   10903

19) Write a query to get total sales and total profit by Country, State and city and sort the sales from highest to lowest??

In [23]:
df_merged.groupby(['Country','State','City'])[['Sales','Profit']].sum().sort_values(by = 'Sales', ascending = False)

                                                                 Sales  Profit
Country        State                              City
United Kingdom England                            London         69230   13931
Germany        Berlin                             Berlin         52555    5942
Austria        Vienna                             Vienna         51844   13207
Spain          Madrid                             Madrid         44981   11129
France         Ile-de-France                      Paris          42245    6680
...                                                                ...     ...
Germany        Hesse                              Friedberg         18       6
France         Provence-Alpes-Côte d'Azur         Sorgues           14       3
               Languedoc-Roussillon-Midi-Pyrénées Sète              14       7
               Auvergne-Rhône-Alpes               Aix-les-Bains     10       4
               Ile-de-France                      Osny               5       2

[1001 rows x 2 columns]

20) Write a query to get total sales and total orderqty by CustomerName sort it by total sales from highest to lowest?

In [24]:
df_merged.groupby('CustomerName')[['Sales','OrderQuantity']].sum().sort_values(by = 'Sales', ascending = False)

                   Sales  OrderQuantity
CustomerName
Angie Massengill   16146            102
Lola Hughes        13191            127
Ashton Charles     13056             63
Isaac David        11271            110
Philip Newsom      10893             80
...                  ...            ...
Alexandra Mahmood     47              2
Max Baker             44              1
Grace Brown           23              1
Jodie Garner          16              1
James Brown           14              2

[792 rows x 2 columns]

21) Identify the top 5 products with the highest sales (by sales amount). Show the product name, total sales, and total qty?

In [25]:
df2.groupby('ProductName')[['Sales','OrderQuantity']].sum().sort_values(by = 'Sales', ascending = False)

                                                    Sales  OrderQuantity
ProductName
Nokia Smart Phone, Full Size                        30645             54
Hamilton Beach Stove, Silver                        16890             33
Cisco Smart Phone, Cordless                         14723             29
Novimex Executive Leather Armchair, Red             13898             44
Cisco Smart Phone, with Caller ID                   13215             25
...                                                   ...            ...
Avery Shipping Labels, Alphabetical                    12              1
Accos Staples, Bulk Pack                               11              2
Smead Shipping Labels, Adjustable                      10              2
Harbour Creations File Folder Labels, Alphabetical      9              2
Novimex Round Labels, Alphabetical                      9              3

[1810 rows x 2 columns]

22) Write a query to get total sales by City having sales greater than 35000?

In [26]:
df_merged.groupby('City')['Sales'].sum().loc[lambda x:x>35000]

City
Berlin    52555
London    69230
Madrid    44981
Paris     42245
Vienna    51844
Name: Sales, dtype: int64

23. Write a query to get total sales by CustomerName having sales greater than 10000?

In [27]:
df_merged.groupby('CustomerName')['Sales'].sum().reset_index().query('Sales > 10000')

         CustomerName  Sales
49   Angie Massengill  16146
70     Ashton Charles  13056
75     Audrey Knowles  10363
90        Bettie Lang  10466
316       Isaac David  11271
379       Joel Peters  10477
499       Lola Hughes  13191
633     Philip Newsom  10893

24. Write a query to get total sales and total profit by shipmode and sort the sales in
ascending order and profit in descending order?

In [28]:
df_merged.groupby('ShipMode')[['Sales','Profit']].sum().sort_values(by = ['Sales','Profit'], ascending = [1,0])

                Sales  Profit
ShipMode
Immediate      131314   17569
Priority       320426   32639
Economy Plus   483965   54336
Economy       1412777  178696

25. Write a query to get total sales for North and central region?

In [29]:
df_merged[df_merged['Region'].isin(['North','Central'])].groupby('Region')['Sales'].sum()

Region
Central    1315253
North       515979
Name: Sales, dtype: int64

26. Write a query to get total sales and total profit for Italy and Spain countries?

In [30]:
df_merged.query("Country in ['Italy','Spain']").groupby('Country')[['Sales','Profit']].sum()

          Sales  Profit
Country
Italy    252742   15802
Spain    249402   47067

27. Write a query to get the total sales and total profit for each year sort the sales from highest to lowest?

In [31]:
df_merged['OrderYear'] = df_merged['OrderDate'].dt.year
df_merged.groupby('OrderYear')[['Sales','Profit']].sum().sort_values(by = 'Sales', ascending = False)

            Sales  Profit
OrderYear
2014       755030   85330
2013       630224   77200
2012       548880   66223
2011       414348   54487

28. Find the top 10 customers who spent the most across all transactions. Display the customer name, total amount spent, and number of orders placed?

In [32]:
df_merged.groupby('CustomerName')[['Sales','OrderQuantity']].sum().sort_values(by='Sales', ascending = False).head(10)

                  Sales  OrderQuantity
CustomerName
Angie Massengill  16146            102
Lola Hughes       13191            127
Ashton Charles    13056             63
Isaac David       11271            110
Philip Newsom     10893             80
Joel Peters       10477            137
Bettie Lang       10466            108
Audrey Knowles    10363             96
Lilly Le Grand     9962             88
Elijah Sodeman     9689            101

29. Write a query to find which products are most preferred by customers based on the total sales. Display customer name, favorite product9 (top 3 products per each customer), and total sales on that product?

In [33]:
customer_sales = df_merged.groupby(['CustomerName','ProductName'])['Sales'].sum().reset_index().sort_values(by = ['CustomerName', 'Sales'],ascending = [1,0])

In [34]:
customer_sales.groupby('CustomerName').head(3)

          CustomerName                                     ProductName  Sales
3        Aaron Bootman                   Brother Fax and Copier, Color   1543
9        Aaron Bootman                     HP Personal Copier, Digital    632
1        Aaron Bootman                      Belkin Keyboard, Erganomic    245
28    Aaron Cunningham                   Eldon File Cart, Single Width    809
30    Aaron Cunningham                          Hon Rocking Chair, Red    392
...                ...                                             ...    ...
7988         Zoe Lowin                  Panasonic Calculator, Wireless    302
7984         Zoe Lowin                        Deflect-O Frame, Durable    214
8002        Zona Meyer                     Hewlett Copy Machine, Color   1060
8008        Zona Meyer                 Stanley Sketch Pad, Water Color    571
8004        Zona Meyer  Novimex Executive Leather Armchair, Adjustable    410

[2322 rows x 3 columns]

30. Write a query to get 7th rank customer name based on total sales? Display customer name, sales amount and rank.

In [35]:
customer_sales = df_merged.groupby('CustomerName')['Sales'].sum().reset_index()
print(customer_sales)

         CustomerName  Sales
0       Aaron Bootman   4281
1    Aaron Cunningham   2463
2         Aaron Davey   2238
3     Aaron Macrossan     81
4         Abbie Perry   1313
..                ...    ...
787        Zara Loton   1614
788        Zara Money   2862
789       Zoe Lanigan   3249
790         Zoe Lowin   1754
791        Zona Meyer   3905

[792 rows x 2 columns]

In [36]:
customer_sales['Rank'] = customer_sales['Sales'].rank(method = 'dense', ascending= False)

In [37]:
result = customer_sales[customer_sales['Rank']==7]
print(result)

   CustomerName  Sales  Rank
90  Bettie Lang  10466   7.0

31. Write query to get total sales and total profit in years 2011 and 2013 Display year wise total sales and total profit?

In [38]:
df_merged[df_merged['OrderYear'].isin([2011, 2013])].groupby('OrderYear')[['Sales', 'Profit']].sum()

            Sales  Profit
OrderYear
2011       414348   54487
2013       630224   77200

32. Write a query to get total sales, total profit and total order qty by country, state, category and sub-category and sort it from highest to lowest based on sales column?

In [41]:
df_merged.groupby(['Country','State','Category','SubCategory'])[['Sales','Profit','OrderQuantity']].sum().reset_index().sort_values(by = 'Sales', ascending = False)

,Country,State,Category,SubCategory,Sales,Profit,OrderQuantity
1318,United Kingdom,England,Furniture,Bookcases,52576,12790,237
1334,United Kingdom,England,Technology,Phones,52262,11124,198
1332,United Kingdom,England,Technology,Copiers,49025,12408,214
1329,United Kingdom,England,Office Supplies,Storage,42752,5987,569
1333,United Kingdom,England,Technology,Machines,33920,7653,187
...,...,...,...,...,...,...,...
76,Belgium,Brussels,Office Supplies,Fasteners,11,3,1
109,Belgium,Limburg,Office Supplies,Labels,10,2,2
895,Netherlands,Limburg,Office Supplies,Envelopes,9,-9,2
174,Finland,Uusimaa,Office Supplies,Labels,9,3,2
832,Italy,Umbria,Office Supplies,Labels,9,4,1

33. write a function to get the region sales dynamically, if we pass any region, that region sales should be displayed?

In [62]:
def get_region_sales(df, region_name):
    region_sales = df.groupby('Region')['Sales'].sum()
    return region_sales.get(region_name, 0)

In [60]:
def get_region_sale(df, region):
    region_data = df[df['Region']==region]
    return region_data['Sales'].sum()

In [63]:
get_region_sales(df_merged, 'North')

np.int64(515979)

34. write a function to get the country sales, profit dynamically, if we pass any country, that country sales, profit should be displayed?

In [99]:
def get_country_profitsales(df, Country):
    profitsales = df.groupby('Country')[['Sales','Profit']].sum()
    return profitsales.loc[Country]

In [100]:
get_country_profitsales(df_merged,'France')

Sales     609683
Profit     70067
Name: France, dtype: int64

35. write a function to get the Category order quantity dynamically, if we pass any Category, that Category order quantity should be displayed.?

In [101]:
def get_Category_OrderQty(df, category_name):
    category_data = df[df['Category']==category_name]
    category_orderqty = category_data['OrderQuantity'].sum()
    return category_orderqty

In [104]:
get_Category_OrderQty(df_merged, 'Technology')

np.int64(5811)

36. write a function to get the City sales and profit dynamically, if we pass any city, that City sales and profit should be displayed?*

In [122]:
def get_CitySnP(df, city_name):
    city_snp = df.groupby('City')[['Sales','Profit']].sum()
    return city_snp.loc[city_name] if city_name in city_snp.index else False

In [128]:
get_CitySnP(df_merged, 'Valence')

Sales     983
Profit    165
Name: Valence, dtype: int64